main:
  - name: Minecraft
    # url: '#about'
    url: https://mc.small09.top
    weight: 1
  - name: 博客
    url: /posts/
    weight: 2
  # - name: 暴论
  #   url: /daily/
  #   weight: 3
  - name: 工具
    url: /tools/
    weight: 4