name: Hugo-Blog-update

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.4.1
        with:
        ssh-private-key: |
          ${{ secrets.BLOG_DEPLOY_KEY }}

      - name: Scan public keys
        run: |
          ssh-keyscan 42.194.190.42 >> ~/.ssh/known_hosts

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: |
          hugo

      - name: update
      run: |
        rsync -av --delete public kushidou@42.194.190.42:22:/home/kushidou/webserver/webs

